# Generated by Django 4.2.16 on 2024-10-16 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('year', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('mileage', models.IntegerField(default=0)),
                ('with_photo', models.BooleanField(blank=True, default=True, null=True)),
                ('volume', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('condition', models.CharField(max_length=32)),
                ('customs', models.CharField(max_length=32)),
                ('availability', models.BooleanField()),
                ('body', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=32)),
                ('registration', models.CharField(max_length=32)),
                ('drive', models.CharField(choices=[('задный', 'задный'), ('передний', 'передний'), ('полный', 'полный')], default='задный', max_length=16)),
                ('engine', models.CharField(choices=[('бензин', 'бензин'), ('газ', 'газ'), ('дизель', 'дизель'), ('электрический', 'электрический')], default='бензин', max_length=16)),
                ('gearbox', models.CharField(choices=[('автомат', 'автомат'), ('механика', 'механика')], default='автомат', max_length=32)),
                ('steering_wheel', models.CharField(choices=[('слева', 'слева'), ('справо', 'справо')], default='слева', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True, verbose_name='rating')),
                ('text', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='store.car')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replace', to='store.rating')),
            ],
        ),
        migrations.CreateModel(
            name='CarPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotel_images/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='store.car')),
            ],
        ),
    ]
